"use client";
import * as React from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getDictionary } from "@/lib/i18n";
import type { Locale } from "@/lib/i18n/config";
import { formatCurrency, type Currency } from "@/lib/relay/currency";
export function RedeemCodeForm({workspaceId,workspaceName,locale,currency}:{workspaceId:number;workspaceName:string;locale:Locale;currency:Currency}){const d=getDictionary(locale).dashboard.components.redeem;const router=useRouter();const[code,setCode]=React.useState("");const[busy,setBusy]=React.useState(false);const[message,setMessage]=React.useState("");const[error,setError]=React.useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setMessage("");setError("");try{const response=await fetch("/api/user/redeem",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code,workspaceId})});const result=await response.json().catch(()=>null);if(!response.ok)throw new Error(result?.error?.message||result?.error||d.error);setMessage(`${result.replayed?d.alreadyCredited:d.added}: ${formatCurrency(Number(result.amount), currency)} ${currency.code}.`);setCode("");router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:d.error)}finally{setBusy(false)}}return <section className="card border border-border bg-card shadow-sm"><div className="card-body gap-4 p-5"><div><h2 className="card-title text-base">{d.title}</h2><p className="text-sm text-muted-foreground">{d.description} <strong>{workspaceName}</strong>.</p></div><form onSubmit={submit} className="flex flex-col gap-3 sm:flex-row sm:items-end"><label className="form-control w-full max-w-md"><span className="label-text mb-2 text-sm">{d.label}</span><Input required value={code} onChange={event=>setCode(event.target.value)} placeholder="CAPI-…" autoComplete="off" disabled={busy}/></label><Button type="submit" disabled={busy||!code.trim()}>{busy?d.redeeming:d.redeem}</Button></form>{error&&<div role="alert" className="alert alert-error py-2 text-sm">{error}</div>}{message&&<div role="status" className="alert alert-success py-2 text-sm">{message}</div>}</div></section>}
