package auth

import "testing"

func TestBunPasswordCompatibility(t *testing.T) {
	// Generated by Bun.password.hash with the previous runtime's options.
	encoded := "$argon2id$v=19$m=65536,t=3,p=1$8a7MRSD+NO0QSMPd2Ih6li7MNCYWhDIfJWLHAyXkvjU$uUoFrfTs+QvgbneYVN6E9nV4MVkC6LRgqaWtgQSaKyA"
	if !CheckPassword(encoded, "legacy-test-password") {
		t.Fatal("Bun password rejected")
	}
	if CheckPassword(encoded, "wrong-password") {
		t.Fatal("wrong password accepted")
	}
	for _, invalid := range []string{
		"$argon2id$v=19$m=0,t=3,p=1$c2FsdA$aGFzaA",
		"$argon2id$v=19$m=999999999,t=3,p=1$c2FsdA$aGFzaA",
		"$argon2id$v=19$m=65536,t=3,p=0$c2FsdA$aGFzaA",
	} {
		if CheckPassword(invalid, "password") {
			t.Fatalf("invalid password format accepted: %s", invalid)
		}
	}
}
